### ISSUE TITLE
Keycloak access denied in tests

### ISSUE THREAD

**Issue by JoelForamitti** [MILA-Wien/collectivo#139]
When the unit tests from the backend request a token, this token is denied by keycloak - breaking the unit tests in https://github.com/MILA-Wien/collectivo/pull/138

The keycloak log says:

```
2023-07-12 16:04:57 2023-07-12 14:04:57,017 WARN  [org.keycloak.events] (executor-thread-45) type=USER_INFO_REQUEST_ERROR, realmId=376010b1-6899-4bdd-939c-cf3c87662d05, clientId=null, userId=null, ipAddress=172.21.0.10, error=access_denied, auth_method=validate_access_token
```

This issue does not affect the usage of collectivo, since tokens always come from the frontend. 

Possible solutions would be:

- Find out why the token is not accepted
- Remove the tests
- Change from validating through keycloak to decoding the JWT token within collectivo (this could also increase performance?) https://stackoverflow.com/questions/59764606/keycloak-decoding-with-public-key-in-python

**Comment by nanu-c** [comment]
The solution for the `test_keycloak_authentication_succeeds` is to create and add an `openid` scope to the keycloak client, see https://keycloak.discourse.group/t/issue-on-userinfo-endpoint-at-keycloak-20/18461/2

`test_keycloak_user_creation` then fails with a different error:

```
Traceback (most recent call last):
  File "/collectivo_app/collectivo/auth/keycloak/tests.py", line 68, in test_keycloak_user_creation
    self.assertEqual(user.keycloak.uuid, self.keycloak_user_id)
AssertionError: UUID('c0ed4d2f-ca12-46bb-83b0-c0e158306d96') != UUID('f9484e48-3251-4d1d-8cd0-ff1e8bfea23e')
```

**Comment by JoelForamitti** [comment]
Great, thanks! I can continue troubleshooting from here.

**Comment by JoelForamitti** [comment]
Ok this solution worked. The error you shared does not appear.
